services:
  - type: web
    name: enhanced-science-trivia-bot
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run start
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
